name: FeliciaCarter.TV
favicon: null
layout_spectrum: 0.10714156297035515
typography_spectrum: 0.8639976980630308
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5940551345702261
  lightness: 0.13230425375513732
  saturation: 0.5684412438422441
  rhythmicContrast: 0.061862984439358115
purpose: []
